### PR TITLE
Beginning tests for methods in User model.

### PR DESCRIPTION
**Pull request by sweetstyle11**

### CODE REVIEW

**Comment by sweetstyle11** [comment]
I just wanted to verify with you about how to hard code in times for writing tests. In our forms we were using 'datetime' with html, but I just wanted to check with you to see what the best way is to actually write that in a test. Looking in psequal, the datetime is stored like this: 2016-03-07 23:37:00.214645. Would this be the best way to write it in tests?

**Comment by sumeetjain** [comment]
To be honest, I'm not sure :/

Give that a try–if it works, let's go with it for now. You can also see if using Ruby's `Time` or `Date` classes to create values for that field works.

**Comment by sweetstyle11** [comment]
I've got a question about fooling Ruby's Time.now method. Right now, all of my tests related to date times pass, but theoretically, as time progresses these tests would presumably fail. In my research I've found some gems, one being Timecop that sounds like people have used to "fool" the Time.now method. Is there a better way to go about doing this without installing a gem?

**Comment by sumeetjain** [comment]
You can use a **stub**. Here's an example of some code you could run in your test file that should override the `now` method for the `Time` class:

```ruby
Time.stub(:now) { Time.new(2016, 11, 23) }
```

This would modify the `Time` class temporarily so that running `Time.now` actually returns my birthday.

This is basically all Timecop does under the good.

**Pull request merged**
